[package]
name = "reson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
logos = { version = "0.14.2" }
