use std::collections::HashMap;
use std::fs::File;
use std::io::Write;
use std::{fmt::Display, fs};

use strum::IntoEnumIterator;

use crate::compiler::Compiler;
use crate::environment::{self, Environment};
use crate::utils::{MachineChoice, PerMachine};

use super::Backend;

const RAW_NAMES: [&str; 6] = [
    "DEPFILE_UNQUOTED",
    "DESC",
    "pool",
    "description",
    "targetdep",
    "dyndep",
];

#[derive(Clone, Copy)]
enum Quoting {
    Both,
    NotShell,
    NotNinja,
    None,
}

impl Default for Quoting {
    fn default() -> Self {
        Quoting::Both
    }
}

#[derive(Clone, Default)]
struct NinjaCommandArg {
    arg: String,
    quoting: Quoting,
}

#[derive(Clone, Default)]
struct NinjaRule {
    rulename: String,
    command: Vec<NinjaCommandArg>,
    args: Vec<NinjaCommandArg>,
    description: String,
}

impl NinjaRule {
    fn new(rule: &str, command: &[String], args: &[String], description: &str) -> Self {
        Self {
            rulename: rule.to_owned(),
            command: command.iter().map(Self::string_to_command_arg).collect(),
            args: args.iter().map(Self::string_to_command_arg).collect(),
            description: description.to_owned(),
        }
    }

    fn string_to_command_arg(c: &String) -> NinjaCommandArg {
        if c == "&&" {
            return NinjaCommandArg {
                arg: c.clone(),
                quoting: Quoting::NotShell,
            };
        } else if c.starts_with('$') {
            let reg = regex::Regex::new(r"\$\{?(\w*)\}?").expect("Failed to buld regex");
            let group = reg.captures(c);
            match group {
                Some(capture) => {
                    if capture.len() > 1 && RAW_NAMES.contains(&&capture[1]) {
                        return NinjaCommandArg {
                            arg: c.clone(),
                            quoting: Quoting::None,
                        };
                    } else {
                        return NinjaCommandArg {
                            arg: c.clone(),
                            quoting: Quoting::NotNinja,
                        };
                    }
                }
                None => {
                    return NinjaCommandArg {
                        arg: c.clone(),
                        quoting: Quoting::NotNinja,
                    }
                }
            }
        }

        NinjaCommandArg {
            arg: c.clone(),
            ..Default::default()
        }
    }
}

#[derive(Clone)]
enum NinjaObject {
    Comment(String),
    Rule(NinjaRule),
}

impl NinjaObject {
    fn quoter(cmd_arg: &NinjaCommandArg) -> String {
        cmd_arg.arg.to_owned()
    }
}

impl Display for NinjaObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NinjaObject::Comment(comment) => {
                for l in comment.split('\n') {
                    write!(f, "# ")?;
                    write!(f, "{}", l)?;
                    writeln!(f)?;
                }

                writeln!(f)
            }

            NinjaObject::Rule(r) => {
                writeln!(f, "rule {}", r.rulename)?;
                let command_args: Vec<String> = r.command.iter().map(Self::quoter).collect();
                writeln!(f, " command = {}\n", command_args.join(" "))
            }
        }
    }
}

#[derive(Clone, Default)]
pub struct NinjaBackend {
    name: String,
    env: Environment,
    rules: Vec<NinjaObject>,
    rule_dict: HashMap<String, NinjaObject>,
}

impl NinjaBackend {
    pub fn new(env: &Environment) -> Self {
        Self {
            env: env.clone(),
            ..Default::default()
        }
    }
}

impl Backend for NinjaBackend {
    fn generate(&mut self) {
        let ninja = environment::Environment::get_ninja_command_and_version(None, None);
        let mut outfilename = self.env.build_dir.clone().unwrap_or_default();
        outfilename.push("build.ninja");
        let mut tmpfilename = self.env.build_dir.clone().unwrap_or_default();
        tmpfilename.push("build.ninja~");
        let mut file = File::create(&tmpfilename)
            .unwrap_or_else(|_| panic!("Failed to create file {:?}", tmpfilename));

        writeln!(&mut file, "# This is the build file for project ")
            .expect("Failed to write to tmp file");
        writeln!(
            &mut file,
            "# This is autogenerated by the reson build system "
        )
        .expect("Failed to write to tmp file");
        writeln!(&mut file, "# Do not edit by hand\n").expect("Failed to write to tmp file");

        // generate rules
        self.generate_rules();

        // generate phony

        self.write_rules(&mut file);

        //
        fs::copy(&tmpfilename, outfilename).expect("Failed to copy temp nija.build to target");
        fs::remove_file(tmpfilename).expect("Failed to remove temp file");
    }

    fn get_name(&self) -> &String {
        &self.name
    }
}

impl NinjaBackend {
    fn write_rules(&self, outfile: &mut File) {
        for r in &self.rules {
            write!(outfile, "{}", r);
        }
    }

    fn generate_rules(&mut self) {
        self.add_rule_comment(NinjaObject::Comment(String::from(
            "Rules for modules scanning",
        )));
        // self.generate_scanner_rules();
        self.add_rule_comment(NinjaObject::Comment(String::from("Rules for compiling")));
        self.generate_compiler_rules();
        self.add_rule_comment(NinjaObject::Comment(String::from("Rules for linking")));
        // self.generate_static_link_rules();
        // self.generate_dynamic_link_rules();
    }

    fn add_rule_comment(&mut self, comment: NinjaObject) {
        self.rules.push(comment);
    }

    fn add_rule(&mut self, rule: NinjaObject) {
        self.rules.push(rule);
    }

    fn generate_scanner_rules(&mut self) {
        let rulename = "depscan";
        if self.rule_dict.contains_key(rulename) {
            return;
        }

        let mut command = Environment::get_build_command();
        command.push(String::from("--internal"));
        command.push(String::from("depscan"));

        let args = vec![
            String::from("$pickfile"),
            String::from("$out"),
            String::from("$in"),
        ];
        let description = String::from("Module Scanner");
        self.add_rule(NinjaObject::Rule(NinjaRule::new(
            rulename,
            &command,
            &args,
            &description,
        )));
    }

    fn generate_compiler_rules(&mut self) {
        // for machine in MachineChoice::iter() {
        // let clist = self.env.get_coredata().get_compilers().to_owned();
        // for (lang, compiler) in &clist[&machine] {
        // if compiler.get_id() == "clang" {}
        let lang = "cpp";
        let compiler = Compiler::new(vec!["gcc".to_owned()], "");
        self.generate_compile_rules_for(lang, compiler);
        // self.generate_pch_rule_for(lang, compiler);
        // }
        // }
    }

    fn generate_compile_rules_for(&mut self, lang: &str, compiler: Compiler) {
        let rule = self.get_compiler_rule_name(lang, MachineChoice::Host);
        let command = compiler.get_exelist();

        let binding = Vec::from(["".to_string()]);
        let args = binding.as_slice();
        let description = format!("Compiling object");

        self.add_rule(NinjaObject::Rule(NinjaRule::new(
            &rule,
            command,
            args,
            &description,
        )));
    }

    fn get_compiler_rule_name(&self, lang: &str, machine: MachineChoice) -> String {
        format!("{}_COMPILER{}", lang, self.get_rule_suffix(machine))
    }

    fn get_rule_suffix(&self, machine: MachineChoice) -> &str {
        PerMachine::<&str>::new("_FOR_BUILD", "").getitem(machine)
    }

    fn generate_pch_rule_for(&mut self, lang: &String, compiler: &Compiler) {}
}
