name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      SCCACHE_GHA_ENABLED: "true"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Nix
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/flake-checker-action@v9
    - uses: DeterminateSystems/magic-nix-cache-action@v8

    # Build
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.6

    - name: build
      run: nix develop --command cargo build
    - name: test
      run: nix develop --command cargo test
