name: coverage

on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    env: 
      SCCACHE_GHA_ENABLED: "true"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: coverage
      run:  nix develop --command cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: true
    # - name: Upload tests
    #   uses: codecov/test-results-action@v1
    #   with:
    #     files: build/meson-logs/testlog.junit.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}
